const { Schema, model } = require("mongoose");

const documentCategorySchema = new Schema({
  name: {
    type: String,
    required: true,
    unique: true,
  },
  code: {
    type: String,
    required: true,
    unique: true,
  },
  description: {
    type: String,
  },
  required: {
    type: Boolean,
    default: false,
  },
  allowedFileTypes: {
    type: [String],
    default: ["application/pdf", "image/jpeg", "image/png"],
  },
  maxFileSize: {
    type: Number,
    default: 10485760, // 10MB
  },
  scoreCategory: {
    type: String,
    enum: [
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "A9",
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
      "B8",
      "B9",
      "B10",
      "B11",
      "B12",
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C7",
      "C8",
      "D1",
      "D2",
      "D3",
      "D4",
      "D5",
      "D6",
      "E1",
      "E2",
      "E3",
      "E4",
      "F1",
      "F2",
      "F3",
      "F4",
      "G1",
      "G2",
      "G3",
      "G4",
      "G5",
      "G6",
      "G7",
      "G8",
      "H1",
      "H2",
      "H3",
      "H4",
      "H5",
      "H6",
      "H7",
      "H8",
      "H9",
      "H10",
      "H11",
      "H12",
      "H13",
      "H14",
      "H15",
      "H16",
      "H17",
      "H18",
      "H19",
      "H20",
      "H21",
      "H22",
      "H23",
      "H24",
      "H25",
      "H26",
      "H27",
      "H28",
      "I1",
      "I2",
      "I3",
      "I4",
      "I5",
      "I6",
      "I7",
      "I8",
      "I9",
      "I10",
      "I11",
      "I12",
      "I13",
      "J1",
      "J2",
      "J3",
      "J4",
      "J5",
      "J6",
      "J7",
      "J8",
      "J9",
      "J10",
      "J11",
      "J12",
      "J13",
      "J14",
      "J15",
      "J16",
      "J17",
      "J18",
      "J19",
      "K1",
      "K2",
      "K3",
      "K4",
      "K5",
      "K6",
      "K7",
      "K8",
      "K9",
      "K10",
      "K11",
      "K12",
      "L1",
      "L2",
      "L3",
      "L4",
      "L5",
      "L6",
      "L7",
      "L8",
    ],
  },
  positions: [
    {
      type: Schema.Types.ObjectId,
      ref: "Position",
    },
  ],
  academicAreas: [
    {
      type: String,
      enum: [
        "Sağlık Bilimleri",
        "Fen Bilimleri ve Matematik",
        "Mühendislik",
        "Ziraat, Orman ve Su Ürünleri",
        "Eğitim Bilimleri",
        "Filoloji",
        "Mimarlık, Planlama ve Tasarım",
        "Sosyal, Beşeri ve İdari Bilimler",
        "Spor Bilimleri",
        "Hukuk",
        "İlahiyat",
        "Güzel Sanatlar",
      ],
    },
  ],
  active: {
    type: Boolean,
    default: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = model("DocumentCategory", documentCategorySchema);
